name: Validate n8n workflow JSON

on:
  push:
    paths:
      - 'workflows/**/*.json'

jobs:
  lint-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate JSON
        run: |
          for f in workflows/*.json; do
            jq empty "$f"
          done
